### PR TITLE
Migrate to httr2

### PR DESCRIPTION
**Pull request by zsmith27**
Thank you for creating this package! I have been interested in having this capability available in R for a number of years. I made a couple suggested changes that I hope will be helpful for maintaining this package into the future.

**Overview of changes:**
1. Refactored existing code to use httr2 instead of httr. [Per httr documentation](https://httr.r-lib.org/): "httr is superseded: only changes necessary to keep it on CRAN will be made. We recommend using [httr2](https://httr2.r-lib.org/) instead."
2. Refactored existing code to simplify the call for NLCD data. I removed many of the `if` `else` calls, which I think will improve readability.

### CODE REVIEW

**Comment by mhweber** [comment]
Thank you @zsmith27 ! Sorry to be slow on issues here - greatly appreciate the PR - will look over shortly!

**Review by mhweber — APPROVED** [review]
These changes look great, appreciated!

**Comment by mhweber** [comment]
@zsmith27 , not sure how I managed to close this w/out merging! But merged now - thanks for the note!

**Comment by zsmith27** [comment]
No problem. I didn't notice until earlier this week.

**Pull request merged**
